[package]
name = "asf-rs"
version = "0.1.0"
authors = ["John Chadwick <john@jchw.io>"]
edition = "2018"

[dependencies]
nom = "6.0"
nom_locate = "3.0.0"
uuid = "0.8.2"

[lib]
name = "asf"
path = "src/lib.rs"

[[bin]]
name = "asfdump"
path = "src/asfdump.rs"
